### ISSUE TITLE
Latest version needs to be run twice to achieve comments expansion

### ISSUE THREAD

**Issue by noto10** [hemiola314/expand-all#5] opened 2022-09-29 17:51 UTC
Thanks for the long-awaited update.

There seems to be a small issue with the latest version. Upon the initial click, it often shows an error message:

![image](https://user-images.githubusercontent.com/13828004/193105475-61eda0c8-80ea-426a-b6b5-ebb4c45b5601.png)

The script stops after that and requires a second click to finish expanding all the comments:

![image](https://user-images.githubusercontent.com/13828004/193105779-61b50b81-1a6d-4770-8405-795e9d36ff32.png)

![image](https://user-images.githubusercontent.com/13828004/193105822-c67b6053-21ef-4774-b87a-e77f26dc86da.png)

**Comment by hemiola314** [comment] 2022-09-30 19:37
I tracked down a URL to this post:
https://www.facebook.com/theguardian/posts/pfbid0322YLJfSvbwQ6YC5nJuby36zTR9ZfJ8rBMvvykRqBY95kwHGCvTVqWhGtWgc8Lczsl

I’m curious how you loaded the content. It appears to not be the above URL, because it’s expanding for you “main content” when the above URL when expanded should isolate itself to “topmost”.

Are you able to reproduce it reliably, at any time? Is it only particular posts (reliably)?

Are you logged in to Facebook? This bookmarklet does not support expansion if you are not logged in.

**Comment by hemiola314** [comment] 2022-10-07 18:05
I'm unable to reproduce (hence, fix) the problem. Another user reported the following URL as having the same problem:

https://www.facebook.com/ExtraFabulousComics/posts/pfbid0CTu53cVuyYrJQQk5NNYrxAcEHyNUtdzyC56687VLCj3YRomfWv6dv4KGpngom1btl

Do you see the problem there?

**Comment by hemiola314** [comment] 2022-10-09 15:03
Apparently geolocation sensitive (different regions get different HTML). Fixed on 2022-10-08.

http://com.hemiola.com/bookmarklet/

**Closed by hemiola314** 2022-10-09 15:03 UTC
